identifier = "com.tauri.dev"
product-name = "sous-chef"
version = "0.1.0"

[build]
before-build-command = "npm run build"
before-dev-command = "npm start"
dev-url = "http://localhost:5173"
frontend-dist = ".."

[[app.windows]]
fullscreen = false
height = 600
resizable = true
title = "SousChef"
width = 800

[app.security]
csp = ""

[bundle]
active = true
targets = "all"
icon = [
	"icons/32x32.png",
	"icons/128x128.png",
	"icons/128x128@2x.png",
	"icons/icon.icns",
	"icons/icon.ico"
]
